export const jobs = [ 
    {
        enterprise: 'Google',
        owner: 'Dev Front End Jr NodeJS e ReactJS',
        description: 'Desenvolvedor Front End Jr NodeJS e ReactJS com experiência em desenvolvimento de aplicações web e mobile. Conhecimento em HTML5, CSS3, JavaScript, ReactJS, NodeJS, React Native, TypeScript, Git, GitHub, SQL, NoSQL, MongoDB, MySQL, PostgreSQL, Docker, AWS, Azure, Google Cloud, CI/CD, TDD, BDD, Scrum, Kanban, Metodologias Ágeis, Clean Code, Clean Architecture, SOLID, Design Patterns, Microservices, REST, GraphQL, API, JWT, OAuth, SSO, SAML, OpenID',
        quantity: 5,
        active: true,
        place: 'Estados Unidos',
        courseId: '8a63260c-f948-415b-a05e-3714f67e7ace',
    },
    {
        enterprise: 'Accenture',
        owner: 'Dev Front End Pleno ReactNative',
        description: 'Desenvolvedor Front End Pleno ReactNative com experiência em desenvolvimento de aplicações web e mobile. Conhecimento em HTML5, CSS3, JavaScript, ReactJS, NodeJS, React Native, TypeScript, Git, GitHub, SQL, NoSQL, MongoDB, MySQL, PostgreSQL, Docker, AWS, Azure, Google Cloud, CI/CD, TDD, BDD, Scrum, Kanban, Metodologias Ágeis, Clean Code, Clean Architecture, SOLID, Design Patterns, Microservices, REST, GraphQL, API, JWT, OAuth, SSO, SAML, OpenID',
        quantity: 2,
        active: true,
        place: 'Recife',
        courseId: '8a63260c-f948-415b-a05e-3714f67e7ace',
    },
    {
        enterprise: 'Meta',
        owner: 'Dev Front End Sr PHP',
        description: 'Desenvolvedor Front End Sr PHP com experiência em desenvolvimento de aplicações web e mobile. Conhecimento em HTML5, CSS3, JavaScript, ReactJS, NodeJS, React Native, TypeScript, Git, GitHub, SQL, NoSQL, MongoDB, MySQL, PostgreSQL, Docker, AWS, Azure, Google Cloud, CI/CD, TDD, BDD, Scrum, Kanban, Metodologias Ágeis, Clean Code, Clean Architecture, SOLID, Design Patterns, Microservices, REST, GraphQL, API, JWT, OAuth, SSO, SAML, OpenID',
        quantity: 6,
        active: true,
        place: 'Estados Unidos',
        courseId: '8a63260c-f948-415b-a05e-3714f67e7ace',
    },
    {
        enterprise: 'Avanade',
        owner: 'Dev Front End Jr JavaScript',
        description: 'Desenvolvedor Front End Jr JavaScript com experiência em desenvolvimento de aplicações web e mobile. Conhecimento em HTML5, CSS3, JavaScript, ReactJS, NodeJS, React Native, TypeScript, Git, GitHub, SQL, NoSQL, MongoDB, MySQL, PostgreSQL, Docker, AWS, Azure, Google Cloud, CI/CD, TDD, BDD, Scrum, Kanban, Metodologias Ágeis, Clean Code, Clean Architecture, SOLID, Design Patterns, Microservices, REST, GraphQL, API, JWT, OAuth, SSO, SAML, OpenID',
        quantity: 1,
        active: false,
        place: 'São Paulo',
        courseId: '8a63260c-f948-415b-a05e-3714f67e7ace',
    },
    {
        enterprise: 'Tesla',
        owner: 'Dev Front End HTML5 e CSS3',
        description: 'Desenvolvedor Front End HTML5 e CSS3 com experiência em desenvolvimento de aplicações web e mobile. Conhecimento em HTML5, CSS3, JavaScript, ReactJS, NodeJS, React Native, TypeScript, Git, GitHub, SQL, NoSQL, MongoDB, MySQL, PostgreSQL, Docker, AWS, Azure, Google Cloud, CI/CD, TDD, BDD, Scrum, Kanban, Metodologias Ágeis, Clean Code, Clean Architecture, SOLID, Design Patterns, Microservices, REST, GraphQL, API, JWT, OAuth, SSO, SAML, OpenID',
        quantity: 9,
        active: true,
        place: 'Canadá',
        courseId: '8a63260c-f948-415b-a05e-3714f67e7ace',
    }
]