/* eslint-disable prettier/prettier */
export const usuarios = [
    {
        firstname: 'System',
        lastname: 'Admin',
        email: 'admin@admin.com',
        password: 'Adm001',
        cpf: '12345678901',
        adress: 'Rua dos bobos, 0',
        vagas: true,
        shared: true,
        published: true,
    },
    {
        firstname: 'Funcionario',
        lastname: 'Senac',
        email: 'senac@example.com',
        password: 'Senac001',
        cpf: '13345678901',
        adress: 'Rua dos bobos, 0',
        vagas: true,
        shared: true,
        published: true,
    },
    {
        firstname: 'Enterprise',
        lastname: 'Business',
        email: 'enterprise@example.com',
        password: 'Enterprise001',
        cpf: '14345678901',
        adress: 'Rua dos bobos, 0',
        vagas: true,
        shared: true,
        published: true,
    },
    {
        firstname: 'User',
        lastname: 'User',
        email: 'user@example.com',
        password: 'User001',
        cpf: '15345678901',
        adress: 'Rua dos bobos, 0',
        vagas: true,
        shared: true,
        published: true,
    }
]
